### ISSUE TITLE
Add process status in video model , use hostname for url field

### ISSUE THREAD

**Issue by linxea** [nus-mtp/zoomable.js#90]
Can you set a boolean field 'hasProcessed' in video model? So I can track if the videos are processed without making multiple api calls.

Also, please store the thumbnailDir in video entry as hostname + pathtoimageurl, e.g. "localhost:1337/upload/vid/123/image.jpeg" instead of directory url + pathtoimageurl e.g. "/user/folder/.tmp/pathtoimageur;".  Same for videoDir and mpdDir. This is to prevent leak of sensitive data and waste of code in the client side to extract the working ur path.

Thanks.

**Comment by jials** [comment]
Done. Will submit the PR
